const tintColorLight = '#006b31';
const tintColorDark = '#5cdf82';

export default {
  light: {
    text: '#1b1c1c',
    textSecondary: '#3d4a3e',
    background: '#fcf9f8',
    surface: '#fcf9f8',
    surfaceContainer: '#f0eded',
    surfaceContainerHigh: '#eae7e7',
    surfaceContainerLow: '#f6f3f2',
    tint: tintColorLight,
    primary: '#006b31',
    primaryContainer: '#008740',
    onPrimary: '#ffffff',
    onPrimaryContainer: '#f7fff3',
    secondary: '#4059aa',
    secondaryContainer: '#8fa7fe',
    onSecondary: '#ffffff',
    onSecondaryContainer: '#1d3989',
    tertiary: '#904821',
    tertiaryContainer: '#af5f36',
    onTertiary: '#ffffff',
    onTertiaryContainer: '#fffbff',
    error: '#ba1a1a',
    errorContainer: '#ffdad6',
    onError: '#ffffff',
    onErrorContainer: '#93000a',
    outline: '#6d7b6d',
    outlineVariant: '#bccabb',
    tabIconDefault: '#6d7b6d',
    tabIconSelected: tintColorLight,
  },
  dark: {
    text: '#f3f0ef',
    textSecondary: '#bccabb',
    background: '#303030',
    surface: '#303030',
    surfaceContainer: '#3d3d3d',
    surfaceContainerHigh: '#474747',
    surfaceContainerLow: '#363636',
    tint: tintColorDark,
    primary: '#5cdf82',
    primaryContainer: '#005224',
    onPrimary: '#00210b',
    onPrimaryContainer: '#7afc9c',
    secondary: '#b6c4ff',
    secondaryContainer: '#264191',
    onSecondary: '#00164e',
    onSecondaryContainer: '#dce1ff',
    tertiary: '#ffb693',
    tertiaryContainer: '#76330d',
    onTertiary: '#351000',
    onTertiaryContainer: '#ffdbcc',
    error: '#ffb4ab',
    errorContainer: '#93000a',
    onError: '#690005',
    onErrorContainer: '#ffdad6',
    outline: '#6d7b6d',
    outlineVariant: '#3d4a3e',
    tabIconDefault: '#bccabb',
    tabIconSelected: tintColorDark,
  },
};